baseurl: "/"
title: 'Johan Rosa'
theme: hugo-theme-cleanwhite
languageCode: en-us
disqusShortname: 'johan-blog'
googleAnalytics: 'UA-151896571-1'
preserveTaxonomyNames: yes
paginate: 5
hasCJKLanguage: yes
showtoc: no
outputs:
  home:
    - HTML
    - RSS
    - Algolia
params:
  SEOTitle: Blog de Johan
  about_me: yes
  addtional_menus:
    - href: /top/cv/
      title: CV
    - href: /top/about/
      title: Quién soy
    - href: /top/archive/
      title: Archivo
  algolia:
    params:
      - categories
      - tags
    vars:
      - title
      - summary
      - date
      - publishdate
      - expirydate
      - permalink
  algolia_apiKey: ''
  algolia_appId: ''
  algolia_indexName: ''
  algolia_search: no
  ba_track_id: ''
  bookmark_link:
    - href: https://martinfowler.com
      title: Martin Fowler
    - href: http://www.servicemesher.com
      title: ServiceMesher
    - href: https://pxhere.com
      title: Pxhere
    - href: https://unsplash.com
      title: unsplash
  bookmarks: no
  description: "Un Blog personal, algunas veces"
  disqus_proxy: ''
  disqus_site: ''
  featured_condition_size: 1
  featured_tags: false
  friend_link:
    - href: http://betaeconomia.blogspot.com/
      title: Nerys Ramírez
  friends: yes
  header_image: img/home_wave.jpg
  image_404: img/404-bg.jpg
  keyword: Johan Rosa, Rstats, R, Ciencia de datos, data science, dataviz
  leancloud_app_id: ''
  leancloud_app_key: ''
  omit_categories: yes
  page_view_conter: no
  reward: no
  sidebar_about_description: Economista, entuciasta de la progrmación con R
  sidebar_avatar: img/johan_avatar.jpeg
  slogan: Notas de un tipo con inquietudes
  social:
    email: johan.rosaperez@gmail.com
    github: https://github.com/johan-rosa
    linkedin: https://www.linkedin.com/in/johan-rosa-72bb0484/
    stackoverflow: https://stackoverflow.com/users/10266675/johan-rosa
    datacamp: https://www.datacamp.com/profile/johanrosaperez
    rss: no
  title_404: Lo siento, no tengo lo que buscas :(
  twikoo_env_id: ''
outputFormats:
  Algolia:
    baseName: algolia
    isPlainText: yes
    mediaType: application/json
    notAlternative: yes
markup:
  highlight:
    style: dracula
  tableOfContents:
    endLevel: 0
    startLevel: 0
