baseurl = "/"
title = "Johan Rosa"
theme = "hugo-theme-cleanwhite"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = "johan-blog"
googleAnalytics = "UA-151896571-1"
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination
hasCJKLanguage = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[outputs]
home = ["HTML", "RSS", "Algolia"]

[params]
  header_image = "img/home_wave.jpg"
  SEOTitle = "Blog de Johan"
  description = "Un Blog personal con contenido de Ciencia de los datos"
  keyword = "Johan Rosa, Rstats, R, Ciencia de datos, data science, dataviz"
  slogan = "Notas de un tipo con inquietudes"

  image_404 = "img/404-bg.jpg"
  title_404 = "Lo siento, no tengo lo que buscas :("
  omit_categories = true
  showtoc = false

  # leancloud storage for page view counter
#  page_view_conter = false 
#  leancloud_app_id = ""
#  leancloud_app_key = ""

  # algolia site search
  algolia_search = false
  algolia_appId = ""
  algolia_indexName = ""
  algolia_apiKey = ""

  # Sidebar settings
  sidebar_about_description = "Economista, Entusiasta de la Programación con R"
  #sidebar_avatar = "img/avatar-zhaohuabing.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`
  sidebar_avatar = "img/johan_avatar.jpeg"      # use absolute URL, seeing it's used in both `/` and `/about/`

  featured_tags = false 
  featured_condition_size = 1 

  # Baidu Analytics
 # ba_track_id = ""
  
  # We need a proxy to access Disqus api in China
  # Follow https://github.com/zhaohuabing/disqus-php-api to set up your own disqus proxy
#  disqus_proxy = ""
#  disqus_site = ""

  #Enable wechat pay & alipay to allow readers send reward money if they like the articles 
  reward = false 
  # reward_guide = "如果这篇文章对你有用,请随意打赏" 

  friends = true
  bookmarks = false
  about_me = true

  # Include any custom CSS and/or JS files, url or relative to /static folder
  #custom_css = ["css/lightbox.css", "https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css", "css/main.css"]
  #custom_js = ["js/lightbox.js", "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js", "js/main.js"]

  # Highlight.js theme
  # demo: https://highlightjs.org/static/demo/
  highlightjs = "dracula"

  [params.social]
  rss            = false 
  email          = "johan.rosaperez@gmail.com"
  #twitter       = "full profile url in twitter"|
  linkedin       = "https://www.linkedin.com/in/johan-rosa-72bb0484/"
  stackoverflow  = "https://stackoverflow.com/users/10266675/johan-rosa"
  github         = "https://github.com/johan-rosa"
  datacamp       = "https://www.datacamp.com/profile/johanrosaperez"
  #wechat         = "your wechat qr code image"

  [[params.friend_link]]
  title = "Nerys Ramírez"
  href =  "http://betaeconomia.blogspot.com/"

#  [[params.bookmark_link]]
#  title =  "Martin Fowler"
#  href =  "https://martinfowler.com"
#  [[params.bookmark_link]]
#  title = "ServiceMesher"
#  href =  "http://www.servicemesher.com"
#  [[params.bookmark_link]]
#  title =  "Pxhere"
#  href = "https://pxhere.com"
#  [[params.bookmark_link]]
#  title = "unsplash"
#  href = "https://unsplash.com"
    [[params.addtional_menus]]
  title =  "Quién soy"
  href =  "/top/about/"
  
  [[params.addtional_menus]]
  title =  "CV"
  href =  "/top/cv/"
  
[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"] 
